name: Candlestick Java API Pipeline

on: push

jobs:
    unit_test_job:
        name: Unit Test
        runs-on: self-hosted
        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Setup Java
              uses: actions/setup-java@v5
              with:
                java-version: '24'
                distribution: 'temurin'
                architecture: x64

            #- name: Set up Maven
            #  uses: stCarolas/setup-maven@v1.5 # Or another suitable Maven setup action
            #  with:
            #    maven-version: '3.8.6'

            - name: Cache Java dependencies
              uses: actions/cache@v4
              with:
                path: ~/.m2/repository
                key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
                restore-keys: |
                    ${{ runner.os }}-maven-
            
            - name: Build Project
              run: |
                  mvn -f demo/pom.xml clean install
                  mkdir artifacts && mkdir coverage
                  cp demo/target/*.jar artifacts/

            - name: Maven Unit Test
              run: |
                  mvn -f demo/pom.xml test
                  cp demo/target/surefire-reports/* artifacts/
                  cp demo/target/site/jacoco/jacoco.xml coverage/
                  cp demo/target/site/jacoco/index.html coverage/

            - name: Archive Unit Test Results
              uses: actions/upload-artifact@v4
              with:
                name: Event Test Result
                path: artifacts/*
                retention-days: 5
                
            - name: Archive Coverage Test Results
              uses: actions/upload-artifact@v4
              with:
                name: Coverage Test Result
                path: coverage/*
                retention-days: 5
    verify_unit_test_job:
        name: Verify Unit Test
        needs: unit_test_job
        runs-on: self-hosted
        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Download Test Results
              uses: actions/download-artifact@v4
              with:
                name: Event Test Result

            - name: Simple Display Results
              run: |
                  ls -ltra
    build_image_job:
        name: Docker Containerization
        needs: unit_test_job
        #if: github.ref == 'refs/head/main'
        runs-on: self-hosted
        steps:
            - name: Download Test Results
              uses: actions/download-artifact@v4
              with:
                name: Event Test Result

            - name: Docker Login
              uses: docker/login-action@v2.2.0
              with:
                username: ${{ vars.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD}}

            - name: Docker Build
              uses: docker/build-push-action@v4
              with:
                context: .
                push: false
                tags: ${{ vars.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}:latest

            - name: Docker Image Testing
              run: |
                  docker run --name mysql-app -itd \
                      -p 3306:3306 \
                      --env=MYSQL_ROOT_PASSWORD=mypassword \
                      ${{ vars.DOCKER_USERNAME }}/${{ vars.MYSQL_DB_NAME }}:latest
                  docker run --name java-api -itd \
                      -p 8080:8080 \
                      --link mysql-app:mysql-app \
                      ${{ vars.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}:latest

                  sleep 300s
                  curl http://localhost:8080/api/test
                  sudo docker stop java-api && sudo docker rm java-api
                  sudo docker stop mysql-app && sudo docker rm mysql-app

            - name: Docker Push
              uses: docker/build-push-action@v4
              with:
                context: .
                push: true
                tags: ${{ vars.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}:latest

            #- name: Docker Logout
            #  run: sudo docker logout https://docker.io
    deploy_image_job:
        name: Deploy Docker Image
        #if: github.ref == 'refs/head/main'
        needs: build_image_job
        outputs:
          APP_INGRESS_URL: ${{ steps.set-ingress-host-id.outputs.APP_INGRESS_HOST}}
        runs-on: self-hosted
        steps:
            - name: Checkout
              uses: actions/checkout@v5
              
            - name: Install Kubectl CLI
              uses: azure/setup-kubectl@v3
              with:
                version: 'v1.33.6'

            - name: Set Kubeconfig
              uses: azure/k8s-set-context@v3
              with:
                method: kubeconfig
                kubeconfig: ${{ secrets.KUBECONFIG }}
                
            - name: Fetch Kubernetes CLuster Details
              run: |
                  kubectl version
                  echo ............................
                  kubectl get nodes

            - name: Replace Token in Manifest files
              uses: cschleiden/replace-tokens@v1
              with:
                tokenPrefix: '_{_'
                tokenSuffix: '_}_'
                files: '["kubernetes/development/*.yaml"]'
              env:
                NAMESPACE: ${{ vars.NAMESPACE }}
                REPLICAS: ${{ vars.REPLICAS}}
                IMAGE: ${{ vars.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}:latest
                MYSQL_USER: ${{ vars.MYSQL_USER }}
                MYSQL_PASS: ${{ vars.MYSQL_PASS }}

            - name: Check Files
              run: |
                  cat kubernetes/development/*.yaml

            - name: Deploy to Dev Env
              run: |
                  kubectl apply -f kubernetes/development

            - name: Set App Ingress Host URL
              id: set-ingress-host-id
              run: |
                  #echo "APP_INGRESS_HOST=$(kubectl -n ${{ vars.NAMESPACE }} get ingress -o json | jq -r '.items[] | .spec.rules[] | .host')" >> "$GITHUB_OUTPUT"
                  #echo $APP_INGRESS_HOST
    integration_test_job:
        name: Dev Integration Testing
        #if: github.ref == 'refs/head/main'
        needs: deploy_image_job
        runs-on: self-hosted
        steps:
            - name: Test URL Output using cURL
              env:
                URL: ${{ needs.deploy_image_job.outputs.APP_INGRESS_URL }}
              run: |
                  echo $URL
                  echo "................................"
                  curl http://$URL
